### ISSUE TITLE
Automatically generate props documentation

### ISSUE THREAD

**Issue by emplums** [primer/components#383]
I've been meaning to get around to this for a while - the props documentation for each component is currently manually updated. I'm sure there would be some way to filter through each component's `.propTypes` object and at least generate a few of the columns for the props documentation table.

**Comment by mxstbr** [comment]
We used [react-docgen](https://github.com/reactjs/react-docgen) to automatically generate the polished.js.org documentation from the source code, including the arguments to the functions. I'm pretty sure it supports PropTypes, so that might be worth investigating to extract them and put them in a table!

**Comment by mxstbr** [comment]
https://github.com/atlassian/extract-react-types looks even better for this!
