### ISSUE TITLE
React does not recognize the `maxWidth` prop on a DOM element when using Box

### ISSUE THREAD

**Issue by Acidic9** [primer/components#416]
When using the Box component with the `maxWidth` prop, I receive an error saying:

> React does not recognize the `maxWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `maxwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM

My code:

```ts
import React from 'react'
import { Box } from '@primer/components'

export default class Home extends React.Component {
  public render() {
    return (
      <div>
        <Box maxWidth={2}>Hello World</Box>
      </div>
    )
  }
}
```

The emotion styles are still applied, but so is the html attribute to the dom.

Am I doing something wrong or is this a bug?

**Comment by broccolini** [comment]
@Acidic9 Hi! the `maxWidth` prop needs a unit such as `px`. Every prop from [styled-system](https://styled-system.com/) (the library we use for our system props) is a CSS prop unless it says otherwise, so using any valid CSS unit will work here. Unsure if anything else in your setup would cause a problem though.

> The emotion styles are still applied, but so is the html attribute to the dom.

FYI we switched to `styled-components` from emotion several versions ago (I think v8 or before) so you may want to update the version you're on.

**Comment by emplums** [comment]
@Acidic9 I believe this is because some props are not getting filtered out of the remaining HTML attributes that get passed to the DOM by styled-components. I've been noticing this with a few other props and need to look into why this is still happening! It shouldn't affect anything besides having to see the ugly warning in your console. Thanks for the heads up :)

**Comment by emplums** [comment]
This should have been cleared up with the 12.0.1 release! Please let me know if you're still seeing this :)
