### ISSUE TITLE
[API] Dropdown button contents - TypeScript

### ISSUE THREAD

**Issue by clayplumridge** [primer/components#699]
For the TypeScript definitions for Dropdown, the `title` element supports more than just `string` by the current implementation. Expanding it to `JSX.Element` would allow for rendering of custom children within the button, including `Octicons` and other elements without any changes to the existing implementation.

**Comment by dmarcey** [comment]
I guess it comes down to - should a consumer be able to pass non-string content in the `title` prop? If so, should we change the name of the prop from `title` (a breaking change), or just update the typing to be what the component actually supports (`React.ReactNode or JSX.Element like @clayplumridge suggests).

Here's a codesandbox that shows the issue (and also another random typing bug with the `icon` prop of `<TextInput />`.

**Comment by emplums** [comment]
Hey! Looking into this now - I think it would be fine to expand the props of `title` here to allow a react node or a string, since there are several cases where you might want to pass in an Octicon. I will update the type definition!

Just a heads up - in the next major release I'm planning on refactoring the Dropdown component to allow users to pass a component to override the entire button used as the summary to allow more flexibility since many of our dropdown buttons do not use the primary styles.
