### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by semantic-project** [primer/components#905]
react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1465)
    at useRef (react.development.js:1504)
    at SelectMenu.js:36
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)

**Comment by emplums** [comment]
Hey @semantic-project could you provide any more details about what you were doing when this happened? This error is pretty common and could be thrown for a number of reasons. We're currently using this component in a few different projects and haven't run into it yet. If you could provide a repro case in a Codepen or Codesandbox that would be super helpful!

**Comment by semantic-project** [comment]
Hey @emplums this happened when I use components such as : Details, Dropdown menu, Select menu
**Exemple :**
`  <Details>
                                                    <Button as="summary">Click me</Button>
                                                    <p>This should show and hide</p>
                                                </Details>`

**Comment by ocean90** [comment]
@emplums I have also noticed the same a few days ago. It should be noted that this only happens with React 17 which based on the current [package.json](https://github.com/primer/components/blob/d91bd49993d9bd4529f99723d03e04a843591ead/package.json#L103-L104) isn't supported yet.

I tried to find the cause for this but wasn't lucky yet. [Here's a sandbox](https://codesandbox.io/s/elegant-glitter-efb4k?file=/src/App.js) where you can see the error. The sandbox also includes a 1:1 copy of the current details implementation only with a `2` suffix. When you replace `<Details>` with `<Details2>` in `<App>` the error is gone. Could it be some build error with rollup? And/or because [React is also a hard dependency](https://github.com/primer/components/blob/d91bd49993d9bd4529f99723d03e04a843591ead/package.json#L60)?

**Comment by jclem** [comment]
I've only had a chance to look at this briefly, but I think this may be due to multiple React versions getting installed, not because of an actual incompatibility. If I copy/paste the exact `<Details>` code, both pre-and-post refactor (at v22), it seems to work fine with React 17.

**Comment by emplums** [comment]
Confirmed that upgrading to 22.0.2 fixes this issue in the sandbox provided by @ocean90
